#:import Animation kivy.animation.Animation
#:import SlideTransition kivy.uix.screenmanager.SlideTransition

<FirebaseAuth>:
    ScreenManager:
        id: screen_manager
        StartScreen:
            id: start_screen
            name: "start_screen"
        LoginScreen:
            id: login_screen
            name: "login_screen"
        RegisterScreen:
            id: register_screen
            name: "register_screen"
